"""Initial schema with decisions table

Revision ID: b2f55e300e27
Revises: 
Create Date: 2026-02-26 15:46:09.015391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2f55e300e27'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('limitations', sa.JSON(), nullable=False),
    sa.Column('rule_version', sa.String(length=20), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.Column('alert_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_index('idx_address_decided_at', 'decisions', ['address', 'decided_at'], unique=False)
    op.create_index('idx_decided_at_action', 'decisions', ['decided_at', 'action'], unique=False)
    op.create_index('idx_risk_level_action', 'decisions', ['risk_level', 'action'], unique=False)
    op.create_index(op.f('ix_decisions_action'), 'decisions', ['action'], unique=False)
    op.create_index(op.f('ix_decisions_address'), 'decisions', ['address'], unique=False)
    op.create_index(op.f('ix_decisions_alert_id'), 'decisions', ['alert_id'], unique=False)
    op.create_index(op.f('ix_decisions_decided_at'), 'decisions', ['decided_at'], unique=False)
    op.create_index(op.f('ix_decisions_risk_level'), 'decisions', ['risk_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decisions_risk_level'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_decided_at'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_alert_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_address'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_action'), table_name='decisions')
    op.drop_index('idx_risk_level_action', table_name='decisions')
    op.drop_index('idx_decided_at_action', table_name='decisions')
    op.drop_index('idx_address_decided_at', table_name='decisions')
    op.drop_table('decisions')
    # ### end Alembic commands ###
